In [1]:
# Basic Import

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Modelling
from sklearn.metrics import mean_absolute_error,r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRFRegressor
import warnings

### Import the CSV Data as Pandas DataFrame

In [2]:
df = pd.read_csv('data/stud.csv')

In [3]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

### Preparing X and Y variables

In [4]:
print("Categories in 'gender' variable:   ",end=" " )
print(df['gender'].unique())

print("Categories in 'race_ethnicity' variables:  ",end=" ")
print(df['race_ethnicity'].unique())

print("Categories in 'parental_level_of_education' variable:",end=" ")
print(df['parental_level_of_education'].unique())

print("Categories in 'lunch' variable    ",end=" ")
print(df['lunch'].unique())

print("Categories in 'test_preparation_course' variable:   ",end=" ")
print(df['test_preparation_course'].unique())

Categories in 'gender' variable:    ['female' 'male']
Categories in 'race_ethnicity' variables:   ['group B' 'group C' 'group A' 'group D' 'group E']
Categories in 'parental_level_of_education' variable: ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
Categories in 'lunch' variable     ['standard' 'free/reduced']
Categories in 'test_preparation_course' variable:    ['none' 'completed']

In [5]:
X = df.drop(columns=['math_score'],axis=1)

In [6]:
y = df['math_score']

In [7]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [8]:
# Create column Transformers with 3 types of transformers

num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
        ("StandardScaler",numeric_transformer,num_features)
    ]
)

In [9]:
X = preprocessor.fit_transform(X)

In [10]:
X

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]])

In [11]:
X.shape

(1000, 19)

In [12]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((800, 19), (200, 19))

### Create an Evaluate Function to give all Metrics after Model Training

In [13]:
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = np.sqrt(mean_squared_error(true,predicted))
    r2_square = r2_score(true,predicted)
    return mae,rmse,r2_square

In [14]:
models = {
    "LinearRegression": LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "K-Neighbors Regressor":KNeighborsRegressor(),
    "Decision Tree":DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRFRegressor":XGBRFRegressor(),
    "CatBoost Regressor":CatBoostRegressor(verbose=False),
    "AdaBoost Regressor":AdaBoostRegressor()
}

model_list = []
r2_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train) # Train Model

    # Make Predictions

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test dataset

    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train,y_train_pred)

    model_test_mae, model_test_rmse, model_test_r2  = evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])


    print("Model Performance For Training Set")
    print("- Root Mean squared Error : {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print("-----------------------------------")

    
    print("Model Performance For Test Set")
    print("- Root Mean squared Error : {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)

    print('='*35)
    print('\n')

LinearRegression
Model Performance For Training Set
- Root Mean squared Error : 5.3231
- Mean Absolute Error: 4.2667
- R2 Score: 0.8743
-----------------------------------
Model Performance For Test Set
- Root Mean squared Error : 5.3940
- Mean Absolute Error: 4.2148
- R2 Score: 0.8804
===================================


Lasso
Model Performance For Training Set
- Root Mean squared Error : 6.5938
- Mean Absolute Error: 5.2063
- R2 Score: 0.8071
-----------------------------------
Model Performance For Test Set
- Root Mean squared Error : 6.5197
- Mean Absolute Error: 5.1579
- R2 Score: 0.8253
===================================


Ridge
Model Performance For Training Set
- Root Mean squared Error : 5.3233
- Mean Absolute Error: 4.2650
- R2 Score: 0.8743
-----------------------------------
Model Performance For Test Set
- Root Mean squared Error : 5.3904
- Mean Absolute Error: 4.2111
- R2 Score: 0.8806
===================================


K-Neighbors Regressor
Model Performance For Training Set
- Root Mean squared Error : 5.7087
- Mean Absolute Error: 4.5157
- R2 Score: 0.8554
-----------------------------------
Model Performance For Test Set
- Root Mean squared Error : 7.2592
- Mean Absolute Error: 5.6360
- R2 Score: 0.7834
===================================


Decision Tree
Model Performance For Training Set
- Root Mean squared Error : 0.2795
- Mean Absolute Error: 0.0187
- R2 Score: 0.9997
-----------------------------------
Model Performance For Test Set
- Root Mean squared Error : 7.7159
- Mean Absolute Error: 6.1750
- R2 Score: 0.7553
===================================


Random Forest Regressor
Model Performance For Training Set
- Root Mean squared Error : 2.2973
- Mean Absolute Error: 1.8272
- R2 Score: 0.9766
-----------------------------------
Model Performance For Test Set
- Root Mean squared Error : 5.9841
- Mean Absolute Error: 4.6312
- R2 Score: 0.8528
===================================


XGBRFRegressor
Model Performance For Training Set
- Root Mean squared Error : 4.7225
- Mean Absolute Error: 3.7905
- R2 Score: 0.9011
-----------------------------------
Model Performance For Test Set
- Root Mean squared Error : 5.7921
- Mean Absolute Error: 4.5142
- R2 Score: 0.8621
===================================


CatBoost Regressor
Model Performance For Training Set
- Root Mean squared Error : 3.0427
- Mean Absolute Error: 2.4054
- R2 Score: 0.9589
-----------------------------------
Model Performance For Test Set
- Root Mean squared Error : 6.0086
- Mean Absolute Error: 4.6125
- R2 Score: 0.8516
===================================


AdaBoost Regressor
Model Performance For Training Set
- Root Mean squared Error : 5.7955
- Mean Absolute Error: 4.7334
- R2 Score: 0.8510
-----------------------------------
Model Performance For Test Set
- Root Mean squared Error : 5.9505
- Mean Absolute Error: 4.5808
- R2 Score: 0.8545
===================================

In [15]:
pd.DataFrame(list(zip(model_list,r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

                Model Name  R2_Score
2                    Ridge  0.880593
0         LinearRegression  0.880433
6           XGBRFRegressor  0.862131
8       AdaBoost Regressor  0.854488
5  Random Forest Regressor  0.852839
7       CatBoost Regressor  0.851632
1                    Lasso  0.825320
3    K-Neighbors Regressor  0.783446
4            Decision Tree  0.755341

In [18]:
cat_features

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='object')